name: Docker Build

on:
  workflow_run:
    workflows: [ 'Run Tests']
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: hathitrust/github_actions/build@v1
        with:
          image: ghcr.io/${{ github.repository }-unstable
          dockerfile: Dockerfile.prod
          tag: ${{ github.sha }}
          push_latest: true
          registry_token: ${{ github.token }}

  # Omit this part if there is no staging environment, or you don't wish to
  # automatically deploy to staging on merge to main
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Deploy to ${{ env.environment }}
      uses: mlibrary/deploy-to-kubernetes@v2
      with:
        registry_username: ${{ github.actor }}
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/${{ github.repository }}-unstable:${{ github.sha }}
        cluster_ca: ${{ secrets.KUBERNETES_CA }}
        cluster_server: ${{ secrets.KUBERNETES_SERVER }}
        namespace_token: ${{ secrets.KUBERNETES_TOKEN }}
        namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
