name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

# This will set the image for a container called 'web' in a deployment called
# 'web'. If you want to do something different on deploy, see
# https://github.com/mlibrary/deploy-to-kubernetes

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to production
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ github.token }}
        image: ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
        cluster_ca: ${{ secrets.KUBERNETES_CA }}
        cluster_server: ${{ secrets.KUBERNETES_SERVER }}
        namespace_token: ${{ secrets.KUBERNETES_TOKEN }}
        namespace: ${{ secrets.KUBERNETES_NAMESPACE }}
